version: '3.8'

services:
  app:
    image: 'webdevops/php-apache-dev:8.1'
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_USER: 'laravel_user'
      MYSQL_PASSWORD: 'your_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
